### ISSUE TITLE
关于论文有些疑惑

### ISSUE THREAD

**Issue by S1aoXuan** [MiaoJieF/MC-Stereo#1]
在论文的消融实验章节，您对Pretrained Feature Extractor作了对比实验，在表格7中是Feature Extractor效果好于Pretrained，但是在论文中您说"预训练增强了提取特征的表征能力，从而有利于立体匹配"。让我有些困惑，您最终0.45epe结果的backbone是用ConvNeXt的预训练模型还是用的resnet模型呢？
论文阅读可能不够细致，如果有理解错误的地方还请海涵

**Comment by MiaoJieF** [comment]
表格7中"Pretrained Feature Extractor"是连起来的，最终0.45epe结果的backbone使用了ConvNeXt的预训练模型

**Comment by S1aoXuan** [comment]
十分感谢
